version: 2

models:
  - name: doner
    description: "The main table for goodle ads done"
    columns:
      - name: adid
        description: "The ad id"
        tests:
          - not_null
      - name: adgroupid
        description: "The ad group id"
        tests:
          - not_null




